#### THIS PLAYBOOK ASSUMES THE SYSTEM WAS BOOTSTRAPPED WITH THE SCRIPT

---
- hosts: localhost
  become: yes

  roles:

    - role: gantsign.git_user
      users:
        - username: michael
          git_user_name: Michael Della Bitta
          git_user_email: mdellabitta@tutanota.com
          git_user_force: yes

    - role: gantsign.intellij
      intellij_edition: ultimate
      users: 
        - username: michael

    - role: gantsign.oh-my-zsh
      oh_my_zsh_plugins:
        - git
        - node
        - npm
        - nvm
        - zsh-autosuggestions
        - zsh-syntax-highlighting
      theme: robbyrussell
      users:
        - username: michael

    - role: gantsign.pyenv
      pyenv_users:
        - michael
    
    - role: gantsign.sdkman
      sdkman_users:
        - michael
    
    - role: geerlingguy.docker
      docker_users:
        - michael


  tasks:

    - name: Increase number of dnf downloads
      community.general.ini_file:
        path:  /etc/dnf/dnf.conf
        section: main
        option: max_parallel_downloads
        value: 10

    - name: Add RPM Fusion free key
      rpm_key:
        key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
        fingerprint: E9A4 91A3 DE24 7814 E7E0 67EA E06F 8ECD D651 FF2E

    - name: Add RPM Fusion nonfree key
      rpm_key:
        key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
        fingerprint: 79BD B88F 9BBF 7391 0FD4 095B 6A2A F961 9484 3C65

    - name: Enable RPM Fusion
      dnf:
        name:
          - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
          - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"

    - name: Add vscodium repo
      yum_repository:
        name: vscodium
        description: VSCodium repository
        baseurl: https://download.vscodium.com/rpms/
        enabled: yes
        gpgcheck: yes
        repo_gpgcheck: yes
        gpgkey: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg
        metadata_expire: 3600

    - name: Add tailscale repo
      get_url:
        url: https://pkgs.tailscale.com/stable/fedora/tailscale.repo
        dest: '/etc/yum.repos.d/tailscale.repo'
        owner: root
        group: root
        mode: 0644

    - name: Install packages
      dnf:
        name:
          - codium
          - ca-certificates
          - curl
          - gnupg
          - redhat-lsb-core
          - containerd.io
          - emacs-nox
          - emacs-yaml-mode
          - tilix
          - zstd
          - tailscale
          - traceroute
          - net-tools
          - rsync
          - ncdu
          - ripgrep
          - jq
          - gnome-tweak-tool
          - chrome-gnome-shell
        state: latest

    - name: Add flathub
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        method: system
      ignore_errors: yes

    - name: Install flathub flatpaks
      community.general.flatpak:
        name:
          - io.gitlab.librewolf-community
          - com.slack.Slack
          - com.todoist.Todoist
          - org.signal.Signal
          - app.ytmdesktop.ytmdesktop
          - us.zoom.Zoom
          - org.gnome.Extensions
        state: present
        remote: flathub
        method: system

    - name: Set git pull strategy
      command: git config --global pull.rebase true
      become: yes
      become_user: michael

    - name: Set git default branch
      command: git config --global init.defaultBranch main
      become: yes
      become_user: michael

    - name: Install pip packages
      pip:
        name:
          - s3cmd
        state: latest

    - name: Install zsh-autosuggestions
      command: git clone https://github.com/zsh-users/zsh-autosuggestions /home/michael/.oh-my-zsh/custom/plugins/zsh-autosuggestions
      become: yes
      become_user: michael
      args:
        creates: /home/michael/.oh-my-zsh/custom/plugins/zsh-autosuggestions

    - name: Install zsh-syntax-highlighting
      command: git clone https://github.com/zsh-users/zsh-syntax-highlighting.git /home/michael/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
      become: yes
      become_user: michael
      args:
        creates: /home/michael/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

    - name: Download Powerlevel10k
      command: "git clone --depth=1 https://github.com/romkatv/powerlevel10k.git /home/michael/.oh-my-zsh/custom/themes/powerlevel10k"
      become: yes
      become_user: michael
      args:
        creates: /home/michael/.oh-my-zsh/custom/themes/powerlevel10k

    - name: Install Powerlevel10k theme
      ansible.builtin.lineinfile:
        path: /home/michael/.zshrc
        regexp: '^ZSH_THEME='
        line: ZSH_THEME="powerlevel10k/powerlevel10k"

    - name: Check if nvm is installed
      stat:
        path: /home/michael/.nvm
      register: nvm_installed

    - name: Download nvm
      command: curl -o /tmp/nvm.sh -s 'https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh'
      when: nvm_installed.stat.exists == False

    - name: Run nvm install script
      command: "sh /tmp/nvm.sh"
      become: yes
      become_user: michael
      args:
        creates: /home/michael/.nvm
      when: nvm_installed.stat.exists == False

    - name: Add nvm to .zshrc
      lineinfile:
        path: /home/michael/.zshrc
        line: export NVM_DIR="$HOME/.nvm"; [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
        insertafter: EOF
        regexp: "nvm.sh"
      when: nvm_installed.stat.exists == False

    - name: Check if aws-cli is installed
      stat:
        path: /usr/local/bin/aws
      register: aws_cli_installed

    - name: Download aws cli
      command: 'curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"'
      when: aws_cli_installed.stat.exists == False

    - name: Unzip aws cli
      command: unzip -u /tmp/awscliv2.zip -d /tmp
      when: aws_cli_installed.stat.exists == False

    - name: Install aws cli
      command: /tmp/aws/install --update
      become: yes
      when: aws_cli_installed.stat.exists == False

    - name: Ensure fonts directory
      file:
        path: /home/michael/.fonts
        state: directory

    - name: MesloLGS NF exists
      shell: "ls /home/michael/.fonts/MesloLGS*NF"
      register: meslolgs_exists
      ignore_errors: yes

    - name: Download MesloLGS Regular
      when: meslolgs_exists is failed
      get_url:
        url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
        dest: "/home/michael/.fonts/MesloLGS NF Regular.ttf"
    
    - name: Download MesloLGS Bold
      when: meslolgs_exists is failed
      get_url:
        url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
        dest: "/home/michael/.fonts/MesloLGS NF Bold.ttf"
    
    - name: Download MesloLGS Italic
      when: meslolgs_exists is failed
      get_url:
        url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
        dest: "/home/michael/.fonts/MesloLGS NF Italic.ttf"
    
    - name: Download MesloLGS Bold Italic
      when: meslolgs_exists is failed
      get_url:
        url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf
        dest: "/home/michael/.fonts/MesloLGS NF Bold Italic.ttf"

    - name: FiraCode exists
      shell: "ls /home/michael/.fonts/Fira*Nerd*Font*Complete*"
      register: firacode_exists
      ignore_errors: yes

    - name: Download FiraCode
      when: firacode_exists is failed
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip
        dest: /home/michael/.fonts/
        remote_src: yes

  handlers:
