---
- hosts: localhost
  tasks:

    - name: Tap fonts cask
      community.general.homebrew_tap:
        name: homebrew/cask-fonts

    - name: Install casks
      community.general.homebrew_cask:
        pkg:
          - 1password
          - bitwarden
          - datagrip
          - firefox
          - gimp
          - intellij-idea
          - ipfs
          - iterm2
          - malwarebytes
          - omnidisksweeper
          - signal
          - slack
          - todoist
          - vscodium
          - eloston-chromium
          - google-chrome
          - librewolf
          - ytmdesktop-youtube-music
          - zoom
          - docker
          - font-fira-code-nerd-font
          - font-meslo-lg-nerd-font
          - rectangle
          - syncthing
          - obsidian
          - tailscale
        state: latest
      
    - name: Install packages
      community.general.homebrew:
        pkg:
          - git
          - pyenv
          - curl
          - gnupg 
          - pinentry-mac
          - emacs
          - awscli
          - zstd
          - ripgrep
          - jq
          - ncdu
          - ansible
          - tmux
        state: latest

    - name: Set pinentry program
      command: git config --global gpg.program gpg
      become: yes
      become_user: michael

    - name: Set git pull strategy
      command: git config --global pull.rebase true
      become: yes
      become_user: michael
      
    - name: Set git default branch
      command: git config --global init.defaultBranch main
      become: yes
      become_user: michael

    - name: Set git name
      command: git config --global user.name "Michael Della Bitta"
      become: yes
      become_user: michael

    - name: Set git email
      command: git config --global user.email "mdellabitta@tutanota.com"
      become: yes
      become_user: michael
          
    - name: Install pip packages
      pip:
        name:
          - docker-compose
          - s3cmd
        state: latest

    - name: Check if oh-my-zsh is installed
      stat: 
        path: /Users/michael/.oh-my-zsh
      register: oh_my_zsh_installed

    - name: Download oh-my-zsh
      command: "curl -o /tmp/oh-my-zsh.sh -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
      when: oh_my_zsh_installed.stat.exists == False

    - name: Install oh-my-zsh
      command: "sh /tmp/oh-my-zsh.sh --unattended --keep-zshrc"
      become: yes
      become_user: michael
      args:
        creates: /Users/michael/.oh-my-zsh

    - name: Install zsh-autosuggestions
      command: git clone https://github.com/zsh-users/zsh-autosuggestions /Users/michael/.oh-my-zsh/custom/plugins/zsh-autosuggestions
      become: yes
      become_user: michael
      args:
        creates: /Users/michael/.oh-my-zsh/custom/plugins/zsh-autosuggestions

    - name: Install zsh-syntax-highlighting
      command: git clone https://github.com/zsh-users/zsh-syntax-highlighting /Users/michael/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
      become: yes
      become_user: michael
      args:
        creates: /Users/michael/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

    - name: Edit omz into .zshrc
      ansible.builtin.blockinfile:
        path: /Users/michael/.zshrc
        create: true
        block: |
          export ZSH="/Users/michael/.oh-my-zsh"
          plugins=(
            git
            node
            npm
            nvm
            zsh-autosuggestions
            zsh-syntax-highlighting
          )
          source $ZSH/oh-my-zsh.sh

    - name: Download Powerlevel10k
      command: "git clone --depth=1 https://github.com/romkatv/powerlevel10k.git /Users/michael/.oh-my-zsh/custom/themes/powerlevel10k"
      become: yes
      become_user: michael
      args:
        creates: /Users/michael/.oh-my-zsh/custom/themes/powerlevel10k

    - name: Install Powerlevel10k theme
      ansible.builtin.lineinfile:
        path: /Users/michael/.zshrc
        regexp: '^ZSH_THEME='
        line: ZSH_THEME="powerlevel10k/powerlevel10k"

    - name: Check if SDKMAN is installed
      stat: 
        path: /Users/michael/.sdkman
      register: sdkman_installed

    - name: Download SDKMAN
      command: "curl -o /tmp/sdkman.sh -s 'https://get.sdkman.io?rcupdate=false'"
      when: sdkman_installed.stat.exists == False

    - name: Install SDKMAN
      command: "sh /tmp/sdkman.sh"
      become: yes
      become_user: michael
      args:
        creates: /Users/michael/.sdkman
      when: sdkman_installed.stat.exists == False

    - name: Add SDKMAN to .zshrc
      lineinfile:
        path: /Users/michael/.zshrc
        line: export SDKMAN_DIR="$HOME/.sdkman"; [[ -s "${SDKMAN_DIR}/bin/sdkman-init.sh" ]] && source "${SDKMAN_DIR}/bin/sdkman-init.sh"
        insertafter: EOF
        regexp: "sdkman-init"
      when: sdkman_installed.stat.exists == False

    - name: Check if nvm is installed
      stat: 
        path: /Users/michael/.nvm
      register: nvm_installed

    - name: Download nvm
      command: curl -o /tmp/nvm.sh -s 'https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh'
      when: nvm_installed.stat.exists == False

    - name: Run nvm install script
      command: "sh /tmp/nvm.sh"
      become: yes
      become_user: michael
      args:
        creates: /Users/michael/.nvm
      when: nvm_installed.stat.exists == False

    - name: Add nvm to .zshrc
      lineinfile:
        path: /Users/michael/.zshrc
        line: export NVM_DIR="$HOME/.nvm"; [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
        insertafter: EOF
        regexp: "nvm.sh"
      when: nvm_installed.stat.exists 
      
    - name: Add pyenv to .zshrc
      ansible.builtin.lineinfile:
        path: /Users/michael/.zshrc
        line: eval "$(pyenv init -)"
        insertafter: EOF
        regexp: "pyenv init"

    - name: Add pyenv to .zprofile
      ansible.builtin.lineinfile:
        create: true
        path: /Users/michael/.zprofile
        line: eval "$(pyenv init --path)"

  handlers:
